name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Git
      run: git fetch --tags

    - name: Get Git Tag
      id: get_tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "::set-output name=tag::$TAG"

    - name: Log in to GHCR
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.11.0
      with:
        context: .
        file: ./Dockerfile
        push: true          
        tags: |
            ghcr.io/${{ github.repository_owner }}/otvali-xray-bot:latest
            ghcr.io/${{ github.repository_owner }}/otvali-xray-bot:${{ steps.get_tag.outputs.tag }}

